# pandas1

In [1]:
import pandas as pd

In [2]:
data_url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/housing/housing.data' #Data URL
df_data = pd.read_csv(data_url, sep='\s+', header=None) #csv 타입 데이터 로드, separate는 빈 공간으로 지정하고, Column은 없음

In [4]:
df_data.head() # 처음 다섯줄 출력

0     1     2   3      4      5     6       7   8      9     10  \
0  0.00632  18.0  2.31   0  0.538  6.575  65.2  4.0900   1  296.0  15.3   
1  0.02731   0.0  7.07   0  0.469  6.421  78.9  4.9671   2  242.0  17.8   
2  0.02729   0.0  7.07   0  0.469  7.185  61.1  4.9671   2  242.0  17.8   
3  0.03237   0.0  2.18   0  0.458  6.998  45.8  6.0622   3  222.0  18.7   
4  0.06905   0.0  2.18   0  0.458  7.147  54.2  6.0622   3  222.0  18.7   

       11    12    13  
0  396.90  4.98  24.0  
1  396.90  9.14  21.6  
2  392.83  4.03  34.7  
3  394.63  2.94  33.4  
4  396.90  5.33  36.2

In [6]:
df_data.columns = ["a","b","c","d","e","f","g","h","i","j","k","l","m","n"]

In [7]:
df_data.head() # category 바꾸기

a     b     c  d      e      f     g       h  i      j     k       l  \
0  0.00632  18.0  2.31  0  0.538  6.575  65.2  4.0900  1  296.0  15.3  396.90   
1  0.02731   0.0  7.07  0  0.469  6.421  78.9  4.9671  2  242.0  17.8  396.90   
2  0.02729   0.0  7.07  0  0.469  7.185  61.1  4.9671  2  242.0  17.8  392.83   
3  0.03237   0.0  2.18  0  0.458  6.998  45.8  6.0622  3  222.0  18.7  394.63   
4  0.06905   0.0  2.18  0  0.458  7.147  54.2  6.0622  3  222.0  18.7  396.90   

      m     n  
0  4.98  24.0  
1  9.14  21.6  
2  4.03  34.7  
3  2.94  33.4  
4  5.33  36.2

In [9]:
print(df_data.values)
type(df_data.values) # numpy로 되어있음

[[6.3200e-03 1.8000e+01 2.3100e+00 ... 3.9690e+02 4.9800e+00 2.4000e+01]
 [2.7310e-02 0.0000e+00 7.0700e+00 ... 3.9690e+02 9.1400e+00 2.1600e+01]
 [2.7290e-02 0.0000e+00 7.0700e+00 ... 3.9283e+02 4.0300e+00 3.4700e+01]
 ...
 [6.0760e-02 0.0000e+00 1.1930e+01 ... 3.9690e+02 5.6400e+00 2.3900e+01]
 [1.0959e-01 0.0000e+00 1.1930e+01 ... 3.9345e+02 6.4800e+00 2.2000e+01]
 [4.7410e-02 0.0000e+00 1.1930e+01 ... 3.9690e+02 7.8800e+00 1.1900e+01]]


numpy.ndarray

# series

In [11]:
from pandas import Series, DataFrame
import pandas as pd

In [12]:
example_obj = Series()

In [13]:
print(example_obj)

Series([], dtype: float64)


# series_example

In [15]:
list_data  = [1,2,3,4,5]

In [16]:
example_obj = Series(data = list_data)

In [17]:
example_obj

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [18]:
list_name = ["a","b","c","d","e"]

In [19]:
example_obj = Series(data = list_data, index = list_name)

In [20]:
example_obj

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [22]:
dict_data = {"a":1,"b":2,"c":3,"d":4,"e":5}

In [25]:
import numpy as np

In [26]:
example_obj = Series(dict_data, dtype=np.float32, name="sh_data")

In [27]:
example_obj

a    1.0
b    2.0
c    3.0
d    4.0
e    5.0
Name: sh_data, dtype: float32

In [28]:
example_obj["a"]

1.0

In [29]:
example_obj["a"]=3.2

In [30]:
example_obj

a    3.2
b    2.0
c    3.0
d    4.0
e    5.0
Name: sh_data, dtype: float32

In [31]:
example_obj.values

array([3.2, 2. , 3. , 4. , 5. ], dtype=float32)

In [32]:
example_obj.index

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')